version: '3'

services:
  app_deploy:
    build: deploy
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://deploy_db:3306/deploy?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: admin
      DB_PASSWORD: 123
    restart: always
    depends_on:
      deploy_db:
          condition: service_healthy
  deploy_db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: deploy
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10